/**
 * Flux Crystals, QQ, and Vacuum System
 *
 * Late-game resource system where:
 * - Flux Crystals are generated from temporal rifts, dragon nesting, and exploration
 * - QQ (Question Cubes) are generated from Logicat rewards > 5
 * - Vacuum is generated by the Vacuum Cleaner, consuming Flux Crystals + QQ
 * - "This Sucks" controls Vacuum generation rate
 * - Void Starer multiplies Blackprint production based on Vacuum level
 *
 * Reference: boosts.js:9439-9774, castle.js:3403-3434
 */

/**
 * Base cost multiplier per vacuum unit for running the Vacuum Cleaner.
 * Each unit of vacuum costs 10 Flux Crystals and 10 QQ.
 * Reference: boosts.js:9433-9436 (Molpy.VacCost)
 */
export const VACUUM_COST_MULTIPLIER = {
  fluxCrystals: 10,
  qq: 10,
} as const;

/**
 * State needed for Vacuum Cleaner processing.
 */
export interface VacuumTickState {
  /** Whether Vacuum Cleaner boost is enabled (toggle) */
  vacuumCleanerEnabled: boolean;
  /** Whether sand is infinite (required for Vacuum Cleaner) */
  sandIsInfinite: boolean;
  /** Current "This Sucks" level (controls generation rate) */
  thisSucksLevel: number;
  /** Available Flux Crystals */
  fluxCrystals: number;
  /** Whether Flux Crystals are infinite */
  fluxCrystalsInfinite: boolean;
  /** Available QQ */
  qq: number;
  /** Whether QQ is infinite */
  qqInfinite: boolean;
  /** Papal 'Dyson' multiplier */
  papalDyson: number;
  /** Whether Black Hole boost is owned */
  hasBlackHole: boolean;
  /** blackhat power level (0 if not owned) */
  blackhatPower: number;
  /** Whether it's a longpix (NP length > 1800) */
  isLongpix: boolean;
  /** Whether Overtime boost is enabled */
  hasOvertime: boolean;
  /** Whether Tractor Beam is enabled */
  hasTractorBeam: boolean;
  /** Current Goats level (for Tractor Beam doubling) */
  goatsLevel: number;
}

/**
 * Result from processing one Vacuum tick.
 */
export interface VacuumTickResult {
  /** Vacuum generated this tick */
  vacuumGenerated: number;
  /** Goats generated this tick (from Tractor Beam) */
  goatsGenerated: number;
  /** Flux Crystals consumed */
  fluxCrystalsSpent: number;
  /** QQ consumed */
  qqSpent: number;
  /** Whether Vacuum Cleaner was active (had resources) */
  wasActive: boolean;
  /** Whether Black Hole should be unlocked (Flux Crystals reached Infinity) */
  shouldUnlockBlackHole: boolean;
}

/**
 * Calculate the Black Hole vacuum multiplier.
 * Without blackhat: 2x
 * With blackhat: floor(2 + 1.03^(2.8^blackhat_level))
 *
 * Reference: castle.js:3424-3425
 */
export function calculateBlackHoleMultiplier(blackhatPower: number): number {
  if (blackhatPower <= 0) return 2;
  return Math.floor(2 + Math.pow(1.03, Math.pow(2.8, blackhatPower)));
}

/**
 * Process Vacuum Cleaner for one mNP tick.
 *
 * The legacy loop (castle.js:3403-3434):
 * 1. Check enabled + infinite sand + can afford base cost
 * 2. Determine loop count (1, or 2 with Overtime on longpix without Tractor Beam)
 * 3. Per loop iteration:
 *    a. Calculate base vacs from This Sucks level × Papal Dyson
 *    b. Cap vacs by available resources (FC/10, QQ/10; or QQ/10M if blackhat>8)
 *    c. Spend FC and QQ proportional to vacs (10 × vacs each)
 *    d. Apply Black Hole multiplier to vacs
 *    e. Either add Goats (Tractor Beam) or add Vacuum
 *    f. Check if FC reached Infinity → unlock Black Hole
 */
export function processVacuumTick(state: VacuumTickState): VacuumTickResult {
  const noResult: VacuumTickResult = {
    vacuumGenerated: 0,
    goatsGenerated: 0,
    fluxCrystalsSpent: 0,
    qqSpent: 0,
    wasActive: false,
    shouldUnlockBlackHole: false,
  };

  if (!state.vacuumCleanerEnabled || !state.sandIsInfinite) return noResult;

  // Must be able to afford at least 1 unit
  if (state.fluxCrystals < VACUUM_COST_MULTIPLIER.fluxCrystals ||
      state.qq < VACUUM_COST_MULTIPLIER.qq) {
    return noResult;
  }

  // Determine loop count: 1 normally, 2 with Overtime on longpix (unless Tractor Beam)
  let sucks = 1;
  if (state.hasOvertime && state.isLongpix && !state.hasTractorBeam) {
    sucks = 2;
  }

  let totalVacuum = 0;
  let totalGoats = 0;
  let totalFCSpent = 0;
  let totalQQSpent = 0;
  let shouldUnlockBH = false;

  // Track remaining resources across loop iterations
  let remainingFC = state.fluxCrystals;
  let remainingQQ = state.qq;

  for (let i = 0; i < sucks; i++) {
    // Calculate base vacuum rate
    let vacs = Math.floor((state.thisSucksLevel || 1) * state.papalDyson);

    // Cap vacs by available resources
    if (state.blackhatPower > 8 && !state.qqInfinite) {
      // Safety mode: cap by FC/10 and QQ/10M to prevent rapid QQ drain
      vacs = Math.min(vacs, Math.floor(remainingFC / VACUUM_COST_MULTIPLIER.fluxCrystals));
      vacs = Math.min(vacs, Math.floor(remainingQQ / 10000000));
    } else {
      vacs = Math.min(vacs, Math.floor(remainingFC / VACUUM_COST_MULTIPLIER.fluxCrystals));
      vacs = Math.min(vacs, Math.floor(remainingQQ / VACUUM_COST_MULTIPLIER.qq));
    }

    if (vacs <= 0) break;

    // Spend resources proportional to vacs
    const fcCost = VACUUM_COST_MULTIPLIER.fluxCrystals * vacs;
    const qqCost = VACUUM_COST_MULTIPLIER.qq * vacs;
    remainingFC -= fcCost;
    remainingQQ -= qqCost;
    totalFCSpent += fcCost;
    totalQQSpent += qqCost;

    // Apply Black Hole multiplier AFTER spending (multiplies output, not cost)
    if (state.hasBlackHole) {
      vacs *= calculateBlackHoleMultiplier(state.blackhatPower);
    }

    // Tractor Beam: add goats instead of vacuum
    if (state.hasTractorBeam) {
      totalGoats += state.goatsLevel; // doubles current goat supply
    } else {
      totalVacuum += vacs;
    }

    // Check if FC reached Infinity → unlock Black Hole
    if (state.fluxCrystalsInfinite) {
      shouldUnlockBH = true;
    }
  }

  return {
    vacuumGenerated: totalVacuum,
    goatsGenerated: totalGoats,
    fluxCrystalsSpent: totalFCSpent,
    qqSpent: totalQQSpent,
    wasActive: totalFCSpent > 0 || totalQQSpent > 0,
    shouldUnlockBlackHole: shouldUnlockBH,
  };
}

/**
 * Cost to increase "This Sucks" level by 1.
 *
 * Reference: boosts.js:9700-9774
 *
 * Vacuum cost: |2000 - n| * n
 * Blackprint cost: floor(n * 1000 * 1.01^(vacuumLevel/100))
 */
export interface ThisSucksCost {
  vacuum: number;
  blackprints: number;
}

/**
 * Calculate the cost to increase This Sucks from current level n.
 */
export function calculateThisSucksIncreaseCost(
  currentLevel: number,
  vacuumLevel: number
): ThisSucksCost {
  const n = currentLevel;
  return {
    vacuum: Math.abs(2000 - n) * n,
    blackprints: Math.floor(n * 1000 * Math.pow(1.01, vacuumLevel / 100)),
  };
}

/**
 * Calculate the cost to decrease This Sucks by 1.
 * Only available if No Sell boost is not active.
 *
 * Reference: boosts.js:9760
 */
export function calculateThisSucksDecreaseCost(currentLevel: number): number {
  return 1000 * currentLevel; // QQ cost
}

/**
 * Whether increasing This Sucks above 4444 should unlock blackhat.
 * Reference: boosts.js:9735
 */
export function shouldUnlockBlackhat(thisSucksLevel: number): boolean {
  return thisSucksLevel >= 4444;
}

/**
 * Flux Crystal generation from Temporal Rift with Flux Surge.
 * Generates (1 + TDE) crystals and halves Flux Surge countdown.
 *
 * Reference: boosts.js:1901-1904
 */
export function calculateFluxSurgeGeneration(hasTimeDilationEngine: boolean): number {
  return hasTimeDilationEngine ? 2 : 1;
}

/**
 * Flux Crystal generation from Temporal Rift (non-Flux Surge, random).
 * Amount: floor(random * (TimeLord.bought - TimeLord.level + 1) * (TDE + 1))
 *
 * Reference: boosts.js:1913-1915
 */
export function calculateRiftFluxGeneration(
  timeLordBought: number,
  timeLordLevel: number,
  hasTimeDilationEngine: boolean,
  random: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;
  return Math.floor(random * (timeLordBought - timeLordLevel + 1) * tdeMultiplier);
}

/**
 * Flux Crystal generation from explorer badge discovery.
 * Amount: floor(AC.level / 1000) * (1 + TDE) * times
 *
 * Reference: boosts.js:7124-7129
 */
export function calculateExplorerFluxGeneration(
  acLevel: number,
  hasTimeDilationEngine: boolean,
  times: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;
  return Math.floor(acLevel / 1000) * tdeMultiplier * times;
}

/**
 * Flux Harvest: converts remaining Temporal Rift uses into flux crystals.
 *
 * For Time Lord < 100: loops through each rift generating random crystals.
 * For Time Lord >= 100: mathematical approximation with Bonemeal multiplier.
 *
 * Reference: boosts.js:9662-9697
 */
export function calculateFluxHarvest(
  timeLordBought: number,
  timeLordLevel: number,
  hasTimeDilationEngine: boolean,
  riftsRemaining: number,
  hasBoneDigger: boolean,
  bonemealPower: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;

  if (timeLordBought < 100) {
    // Loop through each rift
    let total = 0;
    const maxPerRift = timeLordBought - timeLordLevel + 1;
    for (let i = 0; i < riftsRemaining; i++) {
      total += Math.floor(Math.random() * maxPerRift * tdeMultiplier);
    }
    return total;
  }

  // Mathematical approximation for high Time Lord
  const avgPerRift = (timeLordBought - timeLordLevel) / 2 * tdeMultiplier;
  let total = Math.floor(avgPerRift * riftsRemaining);

  // Bonemeal multiplier
  if (hasBoneDigger && bonemealPower > 0) {
    total = Math.floor(total * (1 + bonemealPower / 100));
  }

  return total;
}

/**
 * Flux Crystal generation from 3D Lens at NP 3095+.
 * Generates 1-2 crystals depending on Retroreflector.
 *
 * Reference: castle.js:3203-3211
 */
export function calculate3DLensFlux(
  currentNP: number,
  has3DLens: boolean,
  hasInfinityGoats: boolean,
  hasRetroreflector: boolean
): number {
  if (currentNP < 3095 || !has3DLens || !hasInfinityGoats) return 0;
  return hasRetroreflector ? 2 : 1;
}

/**
 * QQ generation from Logicat rewards.
 * Only generates QQ when rewards > 5. Amount: floor((rewards - 5) * Papal('QQs'))
 *
 * Reference: boosts.js:3609-3611
 */
export function calculateLogicatQQ(
  logicatRewards: number,
  papalQQs: number
): number {
  if (logicatRewards <= 5) return 0;
  return Math.floor((logicatRewards - 5) * papalQQs);
}

/**
 * Void Starer multiplier for Blackprint production.
 * Multiplies by 1.01^(vacuum/100).
 *
 * Reference: boosts.js:9504-9512
 */
export function calculateVoidStareMultiplier(vacuumLevel: number): number {
  return Math.pow(1.01, vacuumLevel / 100);
}

/**
 * Tangled Tesseract Logicat level multiplier.
 * yield = ((2^(p-4)) * p * (p-1) * (p-2)) / 3
 * where p = |tesseract.power|
 *
 * Reference: boosts.js:10209-10226
 */
export function calculateTesseractMultiplier(tesseractPower: number): number {
  const p = Math.abs(tesseractPower);
  if (p < 3) return 0;
  return (Math.pow(2, p - 4) * p * (p - 1) * (p - 2)) / 3;
}

/**
 * Italian Plumber (Mario) QQ generation from AA runs.
 * Opens lvls Question Qubes, using lvls*(lvls+1)/2 total.
 *
 * Reference: boosts.js:9536-9584
 */
export function calculateMarioQQ(marioBought: number): number {
  return marioBought * (marioBought + 1) / 2;
}

/**
 * Italian Plumber upgrade cost.
 * Per level: Vacuum: 1000 * mult, QQ: 50000 * lvls * mult
 *
 * Reference: boosts.js:9586-9599
 */
export interface MarioUpgradeCost {
  vacuum: number;
  qq: number;
}

export function calculateMarioUpgradeCost(
  currentLevels: number,
  upgradeAmount: number
): MarioUpgradeCost {
  return {
    vacuum: 1000 * upgradeAmount,
    qq: 50000 * currentLevels * upgradeAmount,
  };
}
