/**
 * Flux Crystals, QQ, and Vacuum System
 *
 * Late-game resource system where:
 * - Flux Crystals are generated from temporal rifts, dragon nesting, and exploration
 * - QQ (Question Cubes) are generated from Logicat rewards > 5
 * - Vacuum is generated by the Vacuum Cleaner, consuming Flux Crystals + QQ
 * - "This Sucks" controls Vacuum generation rate
 * - Void Starer multiplies Blackprint production based on Vacuum level
 *
 * Reference: boosts.js:9439-9774, castle.js:3403-3434
 */

/**
 * Cost per mNP for running the Vacuum Cleaner.
 * Reference: boosts.js:9433-9436 (Molpy.VacCost)
 */
export const VACUUM_COST_PER_TICK = {
  fluxCrystals: 10,
  qq: 10,
} as const;

/**
 * State needed for Vacuum Cleaner processing.
 */
export interface VacuumTickState {
  /** Whether Vacuum Cleaner boost is enabled (toggle) */
  vacuumCleanerEnabled: boolean;
  /** Current "This Sucks" level (controls generation rate) */
  thisSucksLevel: number;
  /** Available Flux Crystals */
  fluxCrystals: number;
  /** Available QQ */
  qq: number;
  /** Papal 'Dyson' multiplier */
  papalDyson: number;
  /** Whether Black Hole boost is owned */
  hasBlackHole: boolean;
  /** Black Hole bonus multiplier (from blackhat power scaling) */
  blackHoleMultiplier: number;
  /** Whether it's a longpix (NP length > 1800) */
  isLongpix: boolean;
  /** Whether Overtime boost is enabled */
  hasOvertime: boolean;
  /** blackhat power level (for advanced scaling) */
  blackhatPower: number;
}

/**
 * Result from processing one Vacuum tick.
 */
export interface VacuumTickResult {
  /** Vacuum generated this tick */
  vacuumGenerated: number;
  /** Flux Crystals consumed */
  fluxCrystalsSpent: number;
  /** QQ consumed */
  qqSpent: number;
  /** Whether Vacuum Cleaner was active (had resources) */
  wasActive: boolean;
}

/**
 * Process Vacuum Cleaner for one mNP tick.
 * Consumes 10 Flux Crystals + 10 QQ per tick, generates Vacuum based on This Sucks level.
 *
 * Reference: castle.js:3403-3434
 */
export function processVacuumTick(state: VacuumTickState): VacuumTickResult {
  const noResult: VacuumTickResult = {
    vacuumGenerated: 0,
    fluxCrystalsSpent: 0,
    qqSpent: 0,
    wasActive: false,
  };

  if (!state.vacuumCleanerEnabled) return noResult;

  // Check if we can afford the per-tick cost
  if (state.fluxCrystals < VACUUM_COST_PER_TICK.fluxCrystals ||
      state.qq < VACUUM_COST_PER_TICK.qq) {
    return noResult;
  }

  // Prevention logic: if blackhat power > 8, don't spend if it would underflow
  if (state.blackhatPower > 8) {
    if (state.fluxCrystals - VACUUM_COST_PER_TICK.fluxCrystals < 0 ||
        state.qq - VACUUM_COST_PER_TICK.qq < 0) {
      return noResult;
    }
  }

  // Calculate base vacuum generation: This Sucks level (or 1 if 0) * Papal Dyson
  const baseRate = state.thisSucksLevel || 1;
  let vacuumGenerated = Math.floor(baseRate * state.papalDyson);

  // Black Hole multiplier: base 2x, can scale with blackhat
  if (state.hasBlackHole) {
    vacuumGenerated *= state.blackHoleMultiplier;
  }

  // Overtime: double on longpix
  if (state.hasOvertime && state.isLongpix) {
    vacuumGenerated *= 2;
  }

  vacuumGenerated = Math.floor(vacuumGenerated);

  return {
    vacuumGenerated,
    fluxCrystalsSpent: VACUUM_COST_PER_TICK.fluxCrystals,
    qqSpent: VACUUM_COST_PER_TICK.qq,
    wasActive: true,
  };
}

/**
 * Cost to increase "This Sucks" level by 1.
 *
 * Reference: boosts.js:9700-9774
 *
 * Vacuum cost: |2000 - n| * n
 * Blackprint cost: floor(n * 1000 * 1.01^(vacuumLevel/100))
 */
export interface ThisSucksCost {
  vacuum: number;
  blackprints: number;
}

/**
 * Calculate the cost to increase This Sucks from current level n.
 */
export function calculateThisSucksIncreaseCost(
  currentLevel: number,
  vacuumLevel: number
): ThisSucksCost {
  const n = currentLevel;
  return {
    vacuum: Math.abs(2000 - n) * n,
    blackprints: Math.floor(n * 1000 * Math.pow(1.01, vacuumLevel / 100)),
  };
}

/**
 * Calculate the cost to decrease This Sucks by 1.
 * Only available if No Sell boost is not active.
 *
 * Reference: boosts.js:9760
 */
export function calculateThisSucksDecreaseCost(currentLevel: number): number {
  return 1000 * currentLevel; // QQ cost
}

/**
 * Whether increasing This Sucks above 4444 should unlock blackhat.
 * Reference: boosts.js:9735
 */
export function shouldUnlockBlackhat(thisSucksLevel: number): boolean {
  return thisSucksLevel >= 4444;
}

/**
 * Flux Crystal generation from Temporal Rift with Flux Surge.
 * Generates (1 + TDE) crystals and halves Flux Surge countdown.
 *
 * Reference: boosts.js:1901-1904
 */
export function calculateFluxSurgeGeneration(hasTimeDilationEngine: boolean): number {
  return hasTimeDilationEngine ? 2 : 1;
}

/**
 * Flux Crystal generation from Temporal Rift (non-Flux Surge, random).
 * Amount: floor(random * (TimeLord.bought - TimeLord.level + 1) * (TDE + 1))
 *
 * Reference: boosts.js:1913-1915
 */
export function calculateRiftFluxGeneration(
  timeLordBought: number,
  timeLordLevel: number,
  hasTimeDilationEngine: boolean,
  random: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;
  return Math.floor(random * (timeLordBought - timeLordLevel + 1) * tdeMultiplier);
}

/**
 * Flux Crystal generation from explorer badge discovery.
 * Amount: floor(AC.level / 1000) * (1 + TDE) * times
 *
 * Reference: boosts.js:7124-7129
 */
export function calculateExplorerFluxGeneration(
  acLevel: number,
  hasTimeDilationEngine: boolean,
  times: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;
  return Math.floor(acLevel / 1000) * tdeMultiplier * times;
}

/**
 * Flux Harvest: converts remaining Temporal Rift uses into flux crystals.
 *
 * For Time Lord < 100: loops through each rift generating random crystals.
 * For Time Lord >= 100: mathematical approximation with Bonemeal multiplier.
 *
 * Reference: boosts.js:9662-9697
 */
export function calculateFluxHarvest(
  timeLordBought: number,
  timeLordLevel: number,
  hasTimeDilationEngine: boolean,
  riftsRemaining: number,
  hasBoneDigger: boolean,
  bonemealPower: number
): number {
  const tdeMultiplier = hasTimeDilationEngine ? 2 : 1;

  if (timeLordBought < 100) {
    // Loop through each rift
    let total = 0;
    const maxPerRift = timeLordBought - timeLordLevel + 1;
    for (let i = 0; i < riftsRemaining; i++) {
      total += Math.floor(Math.random() * maxPerRift * tdeMultiplier);
    }
    return total;
  }

  // Mathematical approximation for high Time Lord
  const avgPerRift = (timeLordBought - timeLordLevel) / 2 * tdeMultiplier;
  let total = Math.floor(avgPerRift * riftsRemaining);

  // Bonemeal multiplier
  if (hasBoneDigger && bonemealPower > 0) {
    total = Math.floor(total * (1 + bonemealPower / 100));
  }

  return total;
}

/**
 * Flux Crystal generation from 3D Lens at NP 3095+.
 * Generates 1-2 crystals depending on Retroreflector.
 *
 * Reference: castle.js:3203-3211
 */
export function calculate3DLensFlux(
  currentNP: number,
  has3DLens: boolean,
  hasInfinityGoats: boolean,
  hasRetroreflector: boolean
): number {
  if (currentNP < 3095 || !has3DLens || !hasInfinityGoats) return 0;
  return hasRetroreflector ? 2 : 1;
}

/**
 * QQ generation from Logicat rewards.
 * Only generates QQ when rewards > 5. Amount: floor((rewards - 5) * Papal('QQs'))
 *
 * Reference: boosts.js:3609-3611
 */
export function calculateLogicatQQ(
  logicatRewards: number,
  papalQQs: number
): number {
  if (logicatRewards <= 5) return 0;
  return Math.floor((logicatRewards - 5) * papalQQs);
}

/**
 * Void Starer multiplier for Blackprint production.
 * Multiplies by 1.01^(vacuum/100).
 *
 * Reference: boosts.js:9504-9512
 */
export function calculateVoidStareMultiplier(vacuumLevel: number): number {
  return Math.pow(1.01, vacuumLevel / 100);
}
